[[exercise]]
name = "Back Squat"
description = "Full depth barbell back squat"
primary_muscle = "Quadriceps"

[[exercise]]
name = "Bench Press"
description = "Flat bench barbell press"
primary_muscle = "Chest"

[[exercise]]
name = "Incline Bench Press"
description = "Incline bench barbell press"
primary_muscle = "Chest"

[[exercise]]
name = "Close-Grip Bench Press"
description = "Close grip bench barbell press"
primary_muscle = "Chest"

[[exercise]]
name = "Deadlift"
description = "Conventional barbell deadlift"
primary_muscle = "Posterior Chain"

[[exercise]]
name = "Weighted Pull-Up"
primary_muscle = "Back"

[[exercise]]
name = "BW Pull-Up"
primary_muscle = "Back"

[[exercise]]
name = "Incline Chest Press"
primary_muscle = "Chest"

[[exercise]]
name = "Chest Supported Row"
primary_muscle = "Back"

[[exercise]]
name = "Barbell JM Press"
primary_muscle = "Triceps"

[[exercise]]
name = "EZ Bar Preacher Curl"
primary_muscle = "Biceps"

[[exercise]]
name = "Cable Tricep Pushdown"
primary_muscle = "Triceps"

[[exercise]]
name = "Dumbbell Hammer Curl"
primary_muscle = "Biceps"

[[exercise]]
name = "Reverse Dumbbell Wrist Curl"
primary_muscle = "Forearms"
